name: Deploy

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
  pull_request:

jobs:
  build:
    env:
      CONDA_PREFIX: /usr/share/miniconda/

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Setup
      shell: bash -l {0}
      run: |
        conda install jinja2 requests pandas
    - name: Build
      shell: bash -l {0}
      run: |
        python run.py --username ${{ github.actor }} --token ${{ secrets.GH_TOKEN }} --githubrepo ${{ github.repository }} 
        cp stats.csv public/stats.csv
        cp permissions.png public/permissions.png
        cp index.html public/index.html
        cp README.md public/README.md
        cat packages.md >> public/README.md
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        folder: public
